name: Run Tests and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13.3
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with Ruff
        run: ruff check .

      - name: Check code formatting with Ruff
        run: ruff format --check .

      - name: Check docstring style with pydocstyle
        run: pydocstyle --convention=google app/

      - name: Run tests with pytest
        run: |
          PYTHONPATH=. pytest -v
        env:
          PYTHONPATH: .
